image: node:14


before_script:
  - echo "//registry.npmjs.org/:_authToken=${NPM_REGISTRY_TOKEN}" > .npmrc
  - npm ci --cache .npm --prefer-offline

cache:
  key: "follicle" # universal cache
  paths:
    - .npm/

test:
  stage: test
  services:
    - name: mongo:jessie
      alias: mongo
  variables:
    MONGO_HOSTNAME: mongo:27017
  script:
    - npm run coverage
  artifacts:
    name: "follicle_coverage_${CI_BUILD_ID}_${CI_BUILD_REF}"
    when: always
    expire_in: 6 mos
    paths:
      - coverage/
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml



deploy:
  stage: deploy
  script:
    - npm run build
    - npm publish
  only:
    - tags
