image: node:12

services:
 - name: mongo:jessie
   alias: mongo

variables:
  MONGO_HOSTNAME: mongo:27017

before_script:
  - echo "//nexus.tardis.seald.io/repository/npm/:_authToken=${AUTH_TOKEN}" > .npmrc
  - echo "//nexus.tardis.seald.io/repository/npm-hosted/:_authToken=${AUTH_TOKEN}" >> .npmrc
  - echo "registry=https://nexus.tardis.seald.io/repository/npm/" >> .npmrc
  - echo "@seald:registry=https://nexus.tardis.seald.io/repository/npm-hosted/" >> .npmrc
  - echo "always-auth=true" >> .npmrc
  - npm install --silent

test:
  stage: test
  cache:
    paths:
    - ~/.npm
  script:
    - npm run coverage
  artifacts:
    name: "follicle_coverage_${CI_BUILD_ID}_${CI_BUILD_REF}"
    when: always
    expire_in: 6 mos
    paths:
    - coverage/


deploy:
  stage: deploy
  cache:
    paths:
    - ~/.npm
  script:
    - npm run build
    - npm publish
  only:
    - tags
